server {
    listen 8080;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass https://ait-backend-690999534101.us-east1.run.app/;
        proxy_set_header Host ait-backend-690999534101.us-east1.run.app;
        proxy_ssl_server_name on;
    }
}
