services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: ait-backend
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-credentials.json
      - GOOGLE_CLOUD_PROJECT=capestone-487904
    ports:
      - "8001:8000"
    volumes:
      - ./scripts:/app/scripts
      - ./models:/app/models
      - ${HOME}/.config/gcloud/application_default_credentials.json:/app/gcp-credentials.json:ro
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ait-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped